#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primera_entrega.Models.Home
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ExamenNet2017")]
	public partial class DatosSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    partial void InsertTERMICA(TERMICA instance);
    partial void UpdateTERMICA(TERMICA instance);
    partial void DeleteTERMICA(TERMICA instance);
    #endregion
		
		public DatosSqlDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ExamenNet2017ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatosSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<TERMICA> TERMICA
		{
			get
			{
				return this.GetTable<TERMICA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _usuario1;
		
		private string _contrasenia;
		
		private string _perfil;
		
		private string _nombre;
		
		private string _apellido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusuario1Changing(string value);
    partial void Onusuario1Changed();
    partial void OncontraseniaChanging(string value);
    partial void OncontraseniaChanged();
    partial void OnperfilChanging(string value);
    partial void OnperfilChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    #endregion
		
		public usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usuario", Storage="_usuario1", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string usuario1
		{
			get
			{
				return this._usuario1;
			}
			set
			{
				if ((this._usuario1 != value))
				{
					this.Onusuario1Changing(value);
					this.SendPropertyChanging();
					this._usuario1 = value;
					this.SendPropertyChanged("usuario1");
					this.Onusuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenia", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string contrasenia
		{
			get
			{
				return this._contrasenia;
			}
			set
			{
				if ((this._contrasenia != value))
				{
					this.OncontraseniaChanging(value);
					this.SendPropertyChanging();
					this._contrasenia = value;
					this.SendPropertyChanged("contrasenia");
					this.OncontraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string perfil
		{
			get
			{
				return this._perfil;
			}
			set
			{
				if ((this._perfil != value))
				{
					this.OnperfilChanging(value);
					this.SendPropertyChanging();
					this._perfil = value;
					this.SendPropertyChanged("perfil");
					this.OnperfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TERMICA")]
	public partial class TERMICA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NOMBRE_PROD;
		
		private int _CARBON;
		
		private int _HORNOS;
		
		private int _GASES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOMBRE_PRODChanging(string value);
    partial void OnNOMBRE_PRODChanged();
    partial void OnCARBONChanging(int value);
    partial void OnCARBONChanged();
    partial void OnHORNOSChanging(int value);
    partial void OnHORNOSChanged();
    partial void OnGASESChanging(int value);
    partial void OnGASESChanged();
    #endregion
		
		public TERMICA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PROD", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NOMBRE_PROD
		{
			get
			{
				return this._NOMBRE_PROD;
			}
			set
			{
				if ((this._NOMBRE_PROD != value))
				{
					this.OnNOMBRE_PRODChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_PROD = value;
					this.SendPropertyChanged("NOMBRE_PROD");
					this.OnNOMBRE_PRODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARBON", DbType="Int NOT NULL")]
		public int CARBON
		{
			get
			{
				return this._CARBON;
			}
			set
			{
				if ((this._CARBON != value))
				{
					this.OnCARBONChanging(value);
					this.SendPropertyChanging();
					this._CARBON = value;
					this.SendPropertyChanged("CARBON");
					this.OnCARBONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORNOS", DbType="Int NOT NULL")]
		public int HORNOS
		{
			get
			{
				return this._HORNOS;
			}
			set
			{
				if ((this._HORNOS != value))
				{
					this.OnHORNOSChanging(value);
					this.SendPropertyChanging();
					this._HORNOS = value;
					this.SendPropertyChanged("HORNOS");
					this.OnHORNOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GASES", DbType="Int NOT NULL")]
		public int GASES
		{
			get
			{
				return this._GASES;
			}
			set
			{
				if ((this._GASES != value))
				{
					this.OnGASESChanging(value);
					this.SendPropertyChanging();
					this._GASES = value;
					this.SendPropertyChanged("GASES");
					this.OnGASESChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
