<?xml version="1.0" encoding="utf-8"?><Database Name="ExamenNet2017" Class="DatosSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-N5PG0EV\SQLEXPRESS;Initial Catalog=ExamenNet2017;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ExamenNet2017ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.usuario" Member="usuario">
    <Type Name="usuario">
      <Column Name="usuario" Member="usuario1" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contrasenia" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="perfil" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TERMICA" Member="TERMICA">
    <Type Name="TERMICA">
      <Column Name="NOMBRE_PROD" Type="System.String" DbType="VarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CARBON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HORNOS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GASES" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>